langauge: java
jdk:
  - oraclejdk8
- os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
install: true
sudo: required
dist: trusty

cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
  - mvn clean test site